### ISSUE TITLE
Add new sorting features

### ISSUE THREAD

**Issue by boxmein** [boxmein/qdb#7]
New features should be added to customize how the quotes are sorted and filtered, including:
- sort by votes
- show new quotes
- show old quotes
- show hot quotes (ranking algorithm?)
- show my quotes
- show some user's quotes (should this be implemented?)

**Comment by ajloveslily14** [comment]
I think right now we just need something that shows all quotes, the worry about the sorting later.

**Comment by boxmein** [comment]
Implemented:
- sort by votes
- sort by new
- sort by ID
- show my quotes
- show users' quotes (currently public!)

I'll open another issue for the ranking algorithm thing.
